### ISSUE TITLE
左侧菜单层级太高 盖住提示

### ISSUE THREAD

**Issue by yuntian001** [baojunGit/vue-admin-manage#1]
![image](https://user-images.githubusercontent.com/43692243/162696462-43b0778b-29f9-43ba-8f76-673597555ef6.png)

**Comment by baojunGit** [comment]
<img width="1279" alt="Snipaste_2022-04-11_18-15-41" src="https://user-images.githubusercontent.com/39872895/162720032-534723de-2c9c-4621-8930-0d993b91781c.png">
这个问题可以通过改用第三方库的层级来修复，只要在main.ts入口文件增加配置，详情你可以看我更新后的代码
// vxe-table 解决 tooltip 被弹出框遮挡
VxeTable.setup({
  zIndex: 9999
})
